name: Liman SSH and NoVNC Builder
on:
  push:
    branches-ignore:
      - 'releases/*'

jobs:
  naming: 
    runs-on: ubuntu-20.04
    steps:
    - id: naming
      run: |
        [ "$GITHUB_REF" == "refs/heads/master" ] && export PRERELEASE=false || export PRERELEASE=true
        [ "$GITHUB_REF" == "refs/heads/master" ] && export NAME="Release ${{ github.run_number }}" || export NAME="${GITHUB_REF#refs/heads/} release ${{ github.run_number }}"
        [ "$GITHUB_REF" == "refs/heads/master" ] && export TAG_NAME="release.${{ github.run_number }}" || export TAG_NAME="${GITHUB_REF#refs/heads/}.release.${{ github.run_number }}"
        echo "::set-output name=prerelease::${PRERELEASE}"
        echo "::set-output name=name::${NAME}"
        echo "::set-output name=tag_name::${TAG_NAME}"
    outputs:
      prerelease: ${{ steps.naming.outputs.prerelease }}
      name: ${{ steps.naming.outputs.name }}
      tag_name: ${{ steps.naming.outputs.tag_name }}
  build:
    needs: naming
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Make DEB&RPM package
      run: |
        sudo apt install rpm -y
        TMP_DIR=/tmp/liman-ssh-build
        DEBIAN_PATH=$TMP_DIR/DEBIAN
        SERVER_BIN_PATH=$TMP_DIR/liman/webssh
        rm -rf $TMP_DIR
        mkdir $TMP_DIR
        mkdir $DEBIAN_PATH
        mkdir -p $SERVER_BIN_PATH
        cp ./scripts/DEBIAN/control $DEBIAN_PATH/control
        sed -i s/%VERSION%/${{ github.run_number }}/g $DEBIAN_PATH/control
        cat $DEBIAN_PATH/control
        cp ./scripts/DEBIAN/postinst $DEBIAN_PATH/postinst
        chmod 775 $DEBIAN_PATH/postinst
        cp -r . $SERVER_BIN_PATH
        dpkg-deb --build $TMP_DIR
        mv /tmp/liman-ssh-build.deb /tmp/liman-ssh-${{ github.run_number }}.deb
        rm -rf $DEBIAN_PATH
        sed -i s/%VERSION%/${{ github.run_number }}/g scripts/rhel/ssh.spec
        rpmbuild -ba scripts/rhel/ssh.spec --define "_app_dir $TMP_DIR" --define "_rpmdir /tmp" --define "_rpmfilename liman-ssh-${{ github.run_number }}.rpm"
    - name: Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
          files: |
            /tmp/liman-ssh-${{ github.run_number }}.deb
            /tmp/liman-ssh-${{ github.run_number }}.rpm
          name: "${{ needs.naming.outputs.name }}"
          tag_name: "${{ needs.naming.outputs.tag_name }}"
          prerelease: ${{ needs.naming.outputs.prerelease }}